[package]
name = "starroom-pipeline"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
starroom-color = { path = "../starroom-color" }
starroom-color-management = { path = "../starroom-color-management" }
starroom-detail = { path = "../starroom-detail" }
starroom-grading = { path = "../starroom-grading" }
starroom-imageio = { path = "../starroom-imageio" }
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
