[package]
name = "starroom-imageio"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
image = { version = "0.25.10", default-features = false, features = ["jpeg", "png", "tiff"] }
serde.workspace = true
thiserror.workspace = true
